site_name: BigVision Yolodriver Docs
repo_url: https://github.com/bigvisionai/yolodriver
edit_uri: https://github.com/bigvisionai/yolodriver/tree/main/docs
repo_name: bigvisionai/yolodriver

theme:
  name: "material"
#  logo:
#  favicon:
  font:
    text: Roboto

  palette:
    # Palette toggle for light mode
    - scheme: default
      # primary: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      # primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.action.edit
    - content.code.annotate
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.top
    - navigation.expand
    - navigation.footer
    - content.tabs.link  # all code tabs change simultaneously

# Customization
copyright: BigVision AI 2023. All rights reserved.
extra:
  # version:
  #   provider: mike  #  version drop-down menu
  analytics:
    provider: google
    property: G-2M5EHKC0BH
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bigvisionai
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/satyamallick/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/LearnOpenCV
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/LearnOpenCV
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/opencvcourses/yolodriver
#    - icon: fontawesome/brands/python
#      link: https://pypi.org/project/yolodriver/

extra_css:
  - stylesheets/style.css

markdown_extensions:
  # Div text decorators
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - attr_list
  - def_list
  # Syntax highlight
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

  # Button
  - attr_list

  # Content tabs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

  # Highlight
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - mkdocstrings
  - search

# Primary navigation
nav:
  - Home: index.md
